services:
  java-app:
    image: registry.gitlab.com/mu-bd-ce/devcontainers/java:latest
    ports:
      - "8080:8080"
    volumes:
      - ..:/workspace
    command: sleep infinity
    depends_on:
      - mysql

  mysql:
    image: mysql:lts
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pasahitza
      MYSQL_DATABASE: pbl
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: